# Biên dịch file main.cc thành chương trình thực thi 'main'
build:
	g++ main.cc -o main

# Thực thi chương trình 'main'
execute:
	./main

# Xóa các file object (.o) và chương trình thực thi 'main'
clean:
	rm -f *.o
	rm -f main

